-- MySQL Script generated by MySQL Workbench
-- Tue May 18 11:11:30 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_restaurante
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_restaurante
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_restaurante` DEFAULT CHARACTER SET utf8 ;
USE `db_restaurante` ;

-- -----------------------------------------------------
-- Table `db_restaurante`.`TBL_INVENTARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_restaurante`.`TBL_INVENTARIO` (
  `IDPRODUCTO` INT NOT NULL AUTO_INCREMENT,
  `PRODUCTO` VARCHAR(100) NULL,
  `PRECIO` DOUBLE NULL,
  `DIRECCIÓ` VARCHAR(200) NULL,
  PRIMARY KEY (`IDPRODUCTO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_restaurante`.`TBL_ENVIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_restaurante`.`TBL_ENVIOS` (
  `IDENVIO` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPCIÓN_ENVIO` VARCHAR(300) NULL,
  `FECHA` DATE NULL,
  `DIRECCION` VARCHAR(200) NULL,
  PRIMARY KEY (`IDENVIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_restaurante`.`TBL_PEDIDOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_restaurante`.`TBL_PEDIDOS` (
  `ID_PEDIDO` INT NOT NULL AUTO_INCREMENT,
  `DESCRPCION_PEDIDO` VARCHAR(200) NULL,
  `FECHA_PEDIDO` DATE NULL,
  `DIRECCIÓN` VARCHAR(200) NULL,
  PRIMARY KEY (`ID_PEDIDO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_restaurante`.`TBL_FACTURAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_restaurante`.`TBL_FACTURAS` (
  `ID_FACTURA` INT NOT NULL AUTO_INCREMENT,
  `DESCRPCION_FACTURA` VARCHAR(200) NULL,
  `FECHA_FACTURA` DATE NULL,
  `DIRECCION` VARCHAR(200) NULL,
  PRIMARY KEY (`ID_FACTURA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_restaurante`.`TBL_DIRECCIONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_restaurante`.`TBL_DIRECCIONES` (
  `ID_DIRECCION` INT NOT NULL AUTO_INCREMENT,
  `DIRECCION` VARCHAR(200) NULL,
  PRIMARY KEY (`ID_DIRECCION`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
